---
- hosts: "local"
  gather_facts: True
  tasks:
   - name: "install webserver packages"
     ansible.builtin.yum:
       name: "{{ item }}"
       state: "{{ package_state }}"
     loop: "{{ webservers_packages }}"
     tags:
      - "yum"
   - name: "ansible debug facts"
     ansible.builtin.debug:
       msg: "{{ ansible_facts }}"
     tags:
      - "facts"
